### ISSUE TITLE
GitHub Stats

### ISSUE THREAD

**Issue by auriium** [WesternPine/WesternPine#1]
Your github stats block of your readme is scuffed - 

https://camo.githubusercontent.com/9d473f1609233d06b48ff73b01bd008e39ffce02dfceb3f73d473842aa763693/68747470733a2f2f6769746875622d726561646d652d73746174732e636f6465737461636b722e76657263656c2e6170702f6170693f757365726e616d653d5765737465726e50696e652673686f775f69636f6e733d7472756526686964655f626f726465723d66616c7365267468656d653d6461726b

**Comment by WesternPine** [comment]
I'll de-scuff it in the upcoming days. Thank you!

**Comment by WesternPine** [comment]
Issue had to do with the URL that was once valid is no longer an acceptable format. This has since been fixed. Thank you!
